import { Celulares } from "src/app/models/celular";

export const celularesData: Celulares[] = [
  {
    id: 1,
    imagen: "assets/img/celulares/celu1.webp",
    titulo: "Celular",
    precio: 130.99,
    descripcion: "Descubre las últimas innovaciones en el mundo de la telefonía móvil con nuestro curso especializado. Desde las características más avanzadas hasta las tendencias emergentes, este curso te sumergirá en el fascinante universo de los celulares.",
    isCel: true,
  },
  {
    id: 2,
    imagen: "assets/img/celulares/celu2.webp",
    titulo: "Celular 2",
    precio: 150.99,
    descripcion: "Explora el diseño y la funcionalidad de los últimos modelos de smartphones con nuestro curso de tecnología móvil. Desde diseños elegantes hasta potentes funciones, este curso te brindará una perspectiva completa de los avances en la industria de la telefonía.",
    isCel: true,
  },
  {
    id: 3,
    imagen: "assets/img/celulares/celu3.webp",
    titulo: "Celular 3",
    precio: 200.99,
    descripcion: "Sumérgete en el mundo de la telefonía móvil de alta gama con nuestro curso avanzado. Conoce las últimas tendencias en cámaras, procesadores y tecnologías emergentes que están dando forma al futuro de los smartphones.",
    isCel: true,
  },
  {
    id: 4,
    imagen: "assets/img/celulares/celu4.webp",
    titulo: "Celular 4",
    precio: 250.99,
    descripcion: "Descubre las características premium de los smartphones más exclusivos con nuestro curso especializado. Desde pantallas innovadoras hasta capacidades de almacenamiento avanzadas, este curso te llevará a un viaje por las últimas novedades en tecnología móvil.",
    isCel: true,
  },
  {
    id: 5,
    imagen: "assets/img/tablets/tablet1.webp",
    titulo: "Tablet 1",
    precio: 100.99,
    descripcion: "Es una opción versátil y asequible para aquellos que buscan disfrutar de la comodidad de una pantalla táctil más grande. Con su diseño elegante y compacto, esta tablet ofrece un rendimiento fluido y una excelente calidad de imagen. Ya sea que quieras navegar por Internet, ver películas o trabajar en tus tareas diarias, la Tablet 1 te brindará una experiencia satisfactoria.",
    isCel: false,
  },
  {
    id: 6,
    imagen: "assets/img/tablets/tablet2.webp",
    titulo: "Tablet 2",
    precio: 120.99,
    descripcion: "Una compañera perfecta para mantenerte conectado y entretenido sobre la marcha. Con su potente procesador y amplia capacidad de almacenamiento, esta tablet te permite disfrutar de tus aplicaciones favoritas, juegos y contenido multimedia sin problemas. Su diseño ligero y portátil la convierte en la elección ideal para llevar a todas partes. Además, su pantalla de alta resolución garantiza una experiencia visual envolvente.",
    isCel: false,
  },
  {
    id: 7,
    imagen: "assets/img/tablets/tablet3.webp",
    titulo: "Tablet 3",
    precio: 150.49,
    descripcion: "Sumérgete en el mundo de la tecnología. Con su diseño elegante y moderno, esta tablet combina estilo y rendimiento. Equipada con un potente procesador y una amplia memoria, te ofrece la capacidad de realizar múltiples tareas sin esfuerzo y disfrutar de un rendimiento rápido y fluido. Su pantalla de alta definición y colores vibrantes te permiten sumergirte en tus películas, juegos y aplicaciones favoritas con una calidad visual excepcional.",
    isCel: false,
  },
  {
    id: 8,
    imagen: "assets/img/tablets/tablet4.webp",
    titulo: "Tablet 4",
    precio: 180.99,
    descripcion: "Sumérgete en el mundo de la tecnología con la. Con su diseño elegante y moderno, esta tablet combina estilo y rendimiento. Equipada con un potente procesador y una amplia memoria, te ofrece la capacidad de realizar múltiples tareas sin esfuerzo y disfrutar de un rendimiento rápido y fluido. Su pantalla de alta definición y colores vibrantes te permiten sumergirte en tus películas, juegos y aplicaciones favoritas con una calidad visual excepcional.",
    isCel: false,
  },
];
